/*
Navicat MySQL Data Transfer

Source Server         : MY DATABASE
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : phuongxa

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2017-06-29 14:55:41
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for tbl_district
-- ----------------------------
DROP TABLE IF EXISTS `tbl_district`;
CREATE TABLE `tbl_district` (
  `district_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `type` varchar(225) CHARACTER SET utf8 NOT NULL,
  `provincial_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`district_id`)
) ENGINE=InnoDB AUTO_INCREMENT=976 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of tbl_district
-- ----------------------------
INSERT INTO `tbl_district` VALUES ('1', 'Ba Đình', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('2', 'Hoàn Kiếm', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('3', 'Tây Hồ', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('4', 'Long Biên', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('5', 'Cầu Giấy', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('6', 'Đống Đa', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('7', 'Hai Bà Trưng', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('8', 'Hoàng Mai', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('9', 'Thanh Xuân', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('16', 'Sóc Sơn', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('17', 'Đông Anh', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('18', 'Gia Lâm', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('19', 'Từ Liêm', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('20', 'Thanh Trì', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('24', 'Hà Giang', 'Thị Xã', '2');
INSERT INTO `tbl_district` VALUES ('26', 'Đồng Văn', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('27', 'Mèo Vạc', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('28', 'Yên Minh', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('29', 'Quản Bạ', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('30', 'Vị Xuyên', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('31', 'Bắc Mê', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('32', 'Hoàng Su Phì', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('33', 'Xín Mần', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('34', 'Bắc Quang', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('35', 'Quang Bình', 'Huyện', '2');
INSERT INTO `tbl_district` VALUES ('40', 'Cao Bằng', 'Thị Xã', '4');
INSERT INTO `tbl_district` VALUES ('42', 'Bảo Lâm', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('43', 'Bảo Lạc', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('44', 'Thông Nông', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('45', 'Hà Quảng', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('46', 'Trà Lĩnh', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('47', 'Trùng Khánh', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('48', 'Hạ Lang', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('49', 'Quảng Uyên', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('50', 'Phục Hoà', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('51', 'Hoà An', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('52', 'Nguyên Bình', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('53', 'Thạch An', 'Huyện', '4');
INSERT INTO `tbl_district` VALUES ('58', 'Bắc Kạn', 'Thị Xã', '6');
INSERT INTO `tbl_district` VALUES ('60', 'Pác Nặm', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('61', 'Ba Bể', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('62', 'Ngân Sơn', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('63', 'Bạch Thông', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('64', 'Chợ Đồn', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('65', 'Chợ Mới', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('66', 'Na Rì', 'Huyện', '6');
INSERT INTO `tbl_district` VALUES ('70', 'Tuyên Quang', 'Thị Xã', '8');
INSERT INTO `tbl_district` VALUES ('72', 'Nà Hang', 'Huyện', '8');
INSERT INTO `tbl_district` VALUES ('73', 'Chiêm Hóa', 'Huyện', '8');
INSERT INTO `tbl_district` VALUES ('74', 'Hàm Yên', 'Huyện', '8');
INSERT INTO `tbl_district` VALUES ('75', 'Yên Sơn', 'Huyện', '8');
INSERT INTO `tbl_district` VALUES ('76', 'Sơn Dương', 'Huyện', '8');
INSERT INTO `tbl_district` VALUES ('80', 'Lào Cai', 'Thành Phố', '10');
INSERT INTO `tbl_district` VALUES ('82', 'Bát Xát', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('83', 'Mường Khương', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('84', 'Si Ma Cai', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('85', 'Bắc Hà', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('86', 'Bảo Thắng', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('87', 'Bảo Yên', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('88', 'Sa Pa', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('89', 'Văn Bàn', 'Huyện', '10');
INSERT INTO `tbl_district` VALUES ('94', 'Điện Biên Phủ', 'Thành Phố', '11');
INSERT INTO `tbl_district` VALUES ('95', 'Mường Lay', 'Thị Xã', '11');
INSERT INTO `tbl_district` VALUES ('96', 'Mường Nhé', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('97', 'Mường Chà', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('98', 'Tủa Chùa', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('99', 'Tuần Giáo', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('100', 'Điện Biên', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('101', 'Điện Biên Đông', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('102', 'Mường Ảng', 'Huyện', '11');
INSERT INTO `tbl_district` VALUES ('104', 'Lai Châu', 'Thị Xã', '12');
INSERT INTO `tbl_district` VALUES ('106', 'Tam Đường', 'Huyện', '12');
INSERT INTO `tbl_district` VALUES ('107', 'Mường Tè', 'Huyện', '12');
INSERT INTO `tbl_district` VALUES ('108', 'Sìn Hồ', 'Huyện', '12');
INSERT INTO `tbl_district` VALUES ('109', 'Phong Thổ', 'Huyện', '12');
INSERT INTO `tbl_district` VALUES ('110', 'Than Uyên', 'Huyện', '12');
INSERT INTO `tbl_district` VALUES ('111', 'Tân Uyên', 'Huyện', '12');
INSERT INTO `tbl_district` VALUES ('116', 'Sơn La', 'Thành Phố', '14');
INSERT INTO `tbl_district` VALUES ('118', 'Quỳnh Nhai', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('119', 'Thuận Châu', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('120', 'Mường La', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('121', 'Bắc Yên', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('122', 'Phù Yên', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('123', 'Mộc Châu', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('124', 'Yên Châu', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('125', 'Mai Sơn', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('126', 'Sông Mã', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('127', 'Sốp Cộp', 'Huyện', '14');
INSERT INTO `tbl_district` VALUES ('132', 'Yên Bái', 'Thành Phố', '15');
INSERT INTO `tbl_district` VALUES ('133', 'Nghĩa Lộ', 'Thị Xã', '15');
INSERT INTO `tbl_district` VALUES ('135', 'Lục Yên', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('136', 'Văn Yên', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('137', 'Mù Cang Chải', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('138', 'Trấn Yên', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('139', 'Trạm Tấu', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('140', 'Văn Chấn', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('141', 'Yên Bình', 'Huyện', '15');
INSERT INTO `tbl_district` VALUES ('148', 'Hòa Bình', 'Thành Phố', '17');
INSERT INTO `tbl_district` VALUES ('150', 'Đà Bắc', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('151', 'Kỳ Sơn', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('152', 'Lương Sơn', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('153', 'Kim Bôi', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('154', 'Cao Phong', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('155', 'Tân Lạc', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('156', 'Mai Châu', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('157', 'Lạc Sơn', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('158', 'Yên Thủy', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('159', 'Lạc Thủy', 'Huyện', '17');
INSERT INTO `tbl_district` VALUES ('164', 'Thái Nguyên', 'Thành Phố', '19');
INSERT INTO `tbl_district` VALUES ('165', 'Sông Công', 'Thị Xã', '19');
INSERT INTO `tbl_district` VALUES ('167', 'Định Hóa', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('168', 'Phú Lương', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('169', 'Đồng Hỷ', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('170', 'Võ Nhai', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('171', 'Đại Từ', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('172', 'Phổ Yên', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('173', 'Phú Bình', 'Huyện', '19');
INSERT INTO `tbl_district` VALUES ('178', 'Lạng Sơn', 'Thành Phố', '20');
INSERT INTO `tbl_district` VALUES ('180', 'Tràng Định', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('181', 'Bình Gia', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('182', 'Văn Lãng', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('183', 'Cao Lộc', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('184', 'Văn Quan', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('185', 'Bắc Sơn', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('186', 'Hữu Lũng', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('187', 'Chi Lăng', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('188', 'Lộc Bình', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('189', 'Đình Lập', 'Huyện', '20');
INSERT INTO `tbl_district` VALUES ('193', 'Hạ Long', 'Thành Phố', '22');
INSERT INTO `tbl_district` VALUES ('194', 'Móng Cái', 'Thành Phố', '22');
INSERT INTO `tbl_district` VALUES ('195', 'Cẩm Phả', 'Thị Xã', '22');
INSERT INTO `tbl_district` VALUES ('196', 'Uông Bí', 'Thị Xã', '22');
INSERT INTO `tbl_district` VALUES ('198', 'Bình Liêu', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('199', 'Tiên Yên', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('200', 'Đầm Hà', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('201', 'Hải Hà', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('202', 'Ba Chẽ', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('203', 'Vân Đồn', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('204', 'Hoành Bồ', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('205', 'Đông Triều', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('206', 'Yên Hưng', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('207', 'Cô Tô', 'Huyện', '22');
INSERT INTO `tbl_district` VALUES ('213', 'Bắc Giang', 'Thành Phố', '24');
INSERT INTO `tbl_district` VALUES ('215', 'Yên Thế', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('216', 'Tân Yên', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('217', 'Lạng Giang', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('218', 'Lục Nam', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('219', 'Lục Ngạn', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('220', 'Sơn Động', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('221', 'Yên Dũng', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('222', 'Việt Yên', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('223', 'Hiệp Hòa', 'Huyện', '24');
INSERT INTO `tbl_district` VALUES ('227', 'Việt Trì', 'Thành Phố', '25');
INSERT INTO `tbl_district` VALUES ('228', 'Phú Thọ', 'Thị Xã', '25');
INSERT INTO `tbl_district` VALUES ('230', 'Đoan Hùng', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('231', 'Hạ Hoà', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('232', 'Thanh Ba', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('233', 'Phù Ninh', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('234', 'Yên Lập', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('235', 'Cẩm Khê', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('236', 'Tam Nông', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('237', 'Lâm Thao', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('238', 'Thanh Sơn', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('239', 'Thanh Thuỷ', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('240', 'Tân Sơn', 'Huyện', '25');
INSERT INTO `tbl_district` VALUES ('243', 'Vĩnh Yên', 'Thành Phố', '26');
INSERT INTO `tbl_district` VALUES ('244', 'Phúc Yên', 'Thị Xã', '26');
INSERT INTO `tbl_district` VALUES ('246', 'Lập Thạch', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('247', 'Tam Dương', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('248', 'Tam Đảo', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('249', 'Bình Xuyên', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('250', 'Mê Linh', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('251', 'Yên Lạc', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('252', 'Vĩnh Tường', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('253', 'Sông Lô', 'Huyện', '26');
INSERT INTO `tbl_district` VALUES ('256', 'Bắc Ninh', 'Thành Phố', '27');
INSERT INTO `tbl_district` VALUES ('258', 'Yên Phong', 'Huyện', '27');
INSERT INTO `tbl_district` VALUES ('259', 'Quế Võ', 'Huyện', '27');
INSERT INTO `tbl_district` VALUES ('260', 'Tiên Du', 'Huyện', '27');
INSERT INTO `tbl_district` VALUES ('261', 'Từ Sơn', 'Thị Xã', '27');
INSERT INTO `tbl_district` VALUES ('262', 'Thuận Thành', 'Huyện', '27');
INSERT INTO `tbl_district` VALUES ('263', 'Gia Bình', 'Huyện', '27');
INSERT INTO `tbl_district` VALUES ('264', 'Lương Tài', 'Huyện', '27');
INSERT INTO `tbl_district` VALUES ('268', 'Hà Đông', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('269', 'Sơn Tây', 'Thị Xã', '1');
INSERT INTO `tbl_district` VALUES ('271', 'Ba Vì', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('272', 'Phúc Thọ', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('273', 'Đan Phượng', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('274', 'Hoài Đức', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('275', 'Quốc Oai', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('276', 'Thạch Thất', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('277', 'Chương Mỹ', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('278', 'Thanh Oai', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('279', 'Thường Tín', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('280', 'Phú Xuyên', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('281', 'Ứng Hòa', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('282', 'Mỹ Đức', 'Huyện', '1');
INSERT INTO `tbl_district` VALUES ('288', 'Hải Dương', 'Thành Phố', '30');
INSERT INTO `tbl_district` VALUES ('290', 'Chí Linh', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('291', 'Nam Sách', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('292', 'Kinh Môn', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('293', 'Kim Thành', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('294', 'Thanh Hà', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('295', 'Cẩm Giàng', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('296', 'Bình Giang', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('297', 'Gia Lộc', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('298', 'Tứ Kỳ', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('299', 'Ninh Giang', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('300', 'Thanh Miện', 'Huyện', '30');
INSERT INTO `tbl_district` VALUES ('303', 'Hồng Bàng', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('304', 'Ngô Quyền', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('305', 'Lê Chân', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('306', 'Hải An', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('307', 'Kiến An', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('308', 'Đồ Sơn', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('309', 'Kinh Dương', 'Quận', '31');
INSERT INTO `tbl_district` VALUES ('311', 'Thuỷ Nguyên', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('312', 'An Dương', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('313', 'An Lão', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('314', 'Kiến Thụy', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('315', 'Tiên Lãng', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('316', 'Vĩnh Bảo', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('317', 'Cát Hải', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('318', 'Bạch Long Vĩ', 'Huyện', '31');
INSERT INTO `tbl_district` VALUES ('323', 'Hưng Yên', 'Thành Phố', '33');
INSERT INTO `tbl_district` VALUES ('325', 'Văn Lâm', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('326', 'Văn Giang', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('327', 'Yên Mỹ', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('328', 'Mỹ Hào', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('329', 'Ân Thi', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('330', 'Khoái Châu', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('331', 'Kim Động', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('332', 'Tiên Lữ', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('333', 'Phù Cừ', 'Huyện', '33');
INSERT INTO `tbl_district` VALUES ('336', 'Thái Bình', 'Thành Phố', '34');
INSERT INTO `tbl_district` VALUES ('338', 'Quỳnh Phụ', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('339', 'Hưng Hà', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('340', 'Đông Hưng', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('341', 'Thái Thụy', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('342', 'Tiền Hải', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('343', 'Kiến Xương', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('344', 'Vũ Thư', 'Huyện', '34');
INSERT INTO `tbl_district` VALUES ('347', 'Phủ Lý', 'Thành Phố', '35');
INSERT INTO `tbl_district` VALUES ('349', 'Duy Tiên', 'Huyện', '35');
INSERT INTO `tbl_district` VALUES ('350', 'Kim Bảng', 'Huyện', '35');
INSERT INTO `tbl_district` VALUES ('351', 'Thanh Liêm', 'Huyện', '35');
INSERT INTO `tbl_district` VALUES ('352', 'Bình Lục', 'Huyện', '35');
INSERT INTO `tbl_district` VALUES ('353', 'Lý Nhân', 'Huyện', '35');
INSERT INTO `tbl_district` VALUES ('356', 'Nam Định', 'Thành Phố', '36');
INSERT INTO `tbl_district` VALUES ('358', 'Mỹ Lộc', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('359', 'Vụ Bản', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('360', 'Ý Yên', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('361', 'Nghĩa Hưng', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('362', 'Nam Trực', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('363', 'Trực Ninh', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('364', 'Xuân Trường', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('365', 'Giao Thủy', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('366', 'Hải Hậu', 'Huyện', '36');
INSERT INTO `tbl_district` VALUES ('369', 'Ninh Bình', 'Thành Phố', '37');
INSERT INTO `tbl_district` VALUES ('370', 'Tam Điệp', 'Thị Xã', '37');
INSERT INTO `tbl_district` VALUES ('372', 'Nho Quan', 'Huyện', '37');
INSERT INTO `tbl_district` VALUES ('373', 'Gia Viễn', 'Huyện', '37');
INSERT INTO `tbl_district` VALUES ('374', 'Hoa Lư', 'Huyện', '37');
INSERT INTO `tbl_district` VALUES ('375', 'Yên Khánh', 'Huyện', '37');
INSERT INTO `tbl_district` VALUES ('376', 'Kim Sơn', 'Huyện', '37');
INSERT INTO `tbl_district` VALUES ('377', 'Yên Mô', 'Huyện', '37');
INSERT INTO `tbl_district` VALUES ('380', 'Thanh Hóa', 'Thành Phố', '38');
INSERT INTO `tbl_district` VALUES ('381', 'Bỉm Sơn', 'Thị Xã', '38');
INSERT INTO `tbl_district` VALUES ('382', 'Sầm Sơn', 'Thị Xã', '38');
INSERT INTO `tbl_district` VALUES ('384', 'Mường Lát', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('385', 'Quan Hóa', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('386', 'Bá Thước', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('387', 'Quan Sơn', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('388', 'Lang Chánh', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('389', 'Ngọc Lặc', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('390', 'Cẩm Thủy', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('391', 'Thạch Thành', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('392', 'Hà Trung', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('393', 'Vĩnh Lộc', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('394', 'Yên Định', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('395', 'Thọ Xuân', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('396', 'Thường Xuân', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('397', 'Triệu Sơn', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('398', 'Thiệu Hoá', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('399', 'Hoằng Hóa', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('400', 'Hậu Lộc', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('401', 'Nga Sơn', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('402', 'Như Xuân', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('403', 'Như Thanh', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('404', 'Nông Cống', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('405', 'Đông Sơn', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('406', 'Quảng Xương', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('407', 'Tĩnh Gia', 'Huyện', '38');
INSERT INTO `tbl_district` VALUES ('412', 'Vinh', 'Thành Phố', '40');
INSERT INTO `tbl_district` VALUES ('413', 'Cửa Lò', 'Thị Xã', '40');
INSERT INTO `tbl_district` VALUES ('414', 'Thái Hoà', 'Thị Xã', '40');
INSERT INTO `tbl_district` VALUES ('415', 'Quế Phong', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('416', 'Quỳ Châu', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('417', 'Kỳ Sơn', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('418', 'Tương Dương', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('419', 'Nghĩa Đàn', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('420', 'Quỳ Hợp', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('421', 'Quỳnh Lưu', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('422', 'Con Cuông', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('423', 'Tân Kỳ', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('424', 'Anh Sơn', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('425', 'Diễn Châu', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('426', 'Yên Thành', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('427', 'Đô Lương', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('428', 'Thanh Chương', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('429', 'Nghi Lộc', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('430', 'Nam Đàn', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('431', 'Hưng Nguyên', 'Huyện', '40');
INSERT INTO `tbl_district` VALUES ('436', 'Hà Tĩnh', 'Thành Phố', '42');
INSERT INTO `tbl_district` VALUES ('437', 'Hồng Lĩnh', 'Thị Xã', '42');
INSERT INTO `tbl_district` VALUES ('439', 'Hương Sơn', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('440', 'Đức Thọ', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('441', 'Vũ Quang', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('442', 'Nghi Xuân', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('443', 'Can Lộc', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('444', 'Hương Khê', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('445', 'Thạch Hà', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('446', 'Cẩm Xuyên', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('447', 'Kỳ Anh', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('448', 'Lộc Hà', 'Huyện', '42');
INSERT INTO `tbl_district` VALUES ('450', 'Đồng Hới', 'Thành Phố', '44');
INSERT INTO `tbl_district` VALUES ('452', 'Minh Hóa', 'Huyện', '44');
INSERT INTO `tbl_district` VALUES ('453', 'Tuyên Hóa', 'Huyện', '44');
INSERT INTO `tbl_district` VALUES ('454', 'Quảng Trạch', 'Huyện', '44');
INSERT INTO `tbl_district` VALUES ('455', 'Bố Trạch', 'Huyện', '44');
INSERT INTO `tbl_district` VALUES ('456', 'Quảng Ninh', 'Huyện', '44');
INSERT INTO `tbl_district` VALUES ('457', 'Lệ Thủy', 'Huyện', '44');
INSERT INTO `tbl_district` VALUES ('461', 'Đông Hà', 'Thành Phố', '45');
INSERT INTO `tbl_district` VALUES ('462', 'Quảng Trị', 'Thị Xã', '45');
INSERT INTO `tbl_district` VALUES ('464', 'Vĩnh Linh', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('465', 'Hướng Hóa', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('466', 'Gio Linh', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('467', 'Đa Krông', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('468', 'Cam Lộ', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('469', 'Triệu Phong', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('470', 'Hải Lăng', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('471', 'Cồn Cỏ', 'Huyện', '45');
INSERT INTO `tbl_district` VALUES ('474', 'Huế', 'Thành Phố', '46');
INSERT INTO `tbl_district` VALUES ('476', 'Phong Điền', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('477', 'Quảng Điền', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('478', 'Phú Vang', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('479', 'Hương Thủy', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('480', 'Hương Trà', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('481', 'A Lưới', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('482', 'Phú Lộc', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('483', 'Nam Đông', 'Huyện', '46');
INSERT INTO `tbl_district` VALUES ('490', 'Liên Chiểu', 'Quận', '48');
INSERT INTO `tbl_district` VALUES ('491', 'Thanh Khê', 'Quận', '48');
INSERT INTO `tbl_district` VALUES ('492', 'Hải Châu', 'Quận', '48');
INSERT INTO `tbl_district` VALUES ('493', 'Sơn Trà', 'Quận', '48');
INSERT INTO `tbl_district` VALUES ('494', 'Ngũ Hành Sơn', 'Quận', '48');
INSERT INTO `tbl_district` VALUES ('495', 'Cẩm Lệ', 'Quận', '48');
INSERT INTO `tbl_district` VALUES ('497', 'Hoà Vang', 'Huyện', '48');
INSERT INTO `tbl_district` VALUES ('498', 'Hoàng Sa', 'Huyện', '48');
INSERT INTO `tbl_district` VALUES ('502', 'Tam Kỳ', 'Thành Phố', '49');
INSERT INTO `tbl_district` VALUES ('503', 'Hội An', 'Thành Phố', '49');
INSERT INTO `tbl_district` VALUES ('504', 'Tây Giang', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('505', 'Đông Giang', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('506', 'Đại Lộc', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('507', 'Điện Bàn', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('508', 'Duy Xuyên', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('509', 'Quế Sơn', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('510', 'Nam Giang', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('511', 'Phước Sơn', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('512', 'Hiệp Đức', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('513', 'Thăng Bình', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('514', 'Tiên Phước', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('515', 'Bắc Trà My', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('516', 'Nam Trà My', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('517', 'Núi Thành', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('518', 'Phú Ninh', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('519', 'Nông Sơn', 'Huyện', '49');
INSERT INTO `tbl_district` VALUES ('522', 'Quảng Ngãi', 'Thành Phố', '51');
INSERT INTO `tbl_district` VALUES ('524', 'Bình Sơn', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('525', 'Trà Bồng', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('526', 'Tây Trà', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('527', 'Sơn Tịnh', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('528', 'Tư Nghĩa', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('529', 'Sơn Hà', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('530', 'Sơn Tây', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('531', 'Minh Long', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('532', 'Nghĩa Hành', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('533', 'Mộ Đức', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('534', 'Đức Phổ', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('535', 'Ba Tơ', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('536', 'Lý Sơn', 'Huyện', '51');
INSERT INTO `tbl_district` VALUES ('540', 'Qui Nhơn', 'Thành Phố', '52');
INSERT INTO `tbl_district` VALUES ('542', 'An Lão', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('543', 'Hoài Nhơn', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('544', 'Hoài Ân', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('545', 'Phù Mỹ', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('546', 'Vĩnh Thạnh', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('547', 'Tây Sơn', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('548', 'Phù Cát', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('549', 'An Nhơn', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('550', 'Tuy Phước', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('551', 'Vân Canh', 'Huyện', '52');
INSERT INTO `tbl_district` VALUES ('555', 'Tuy Hòa', 'Thành Phố', '54');
INSERT INTO `tbl_district` VALUES ('557', 'Sông Cầu', 'Thị Xã', '54');
INSERT INTO `tbl_district` VALUES ('558', 'Đồng Xuân', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('559', 'Tuy An', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('560', 'Sơn Hòa', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('561', 'Sông Hinh', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('562', 'Tây Hoà', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('563', 'Phú Hoà', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('564', 'Đông Hoà', 'Huyện', '54');
INSERT INTO `tbl_district` VALUES ('568', 'Nha Trang', 'Thành Phố', '56');
INSERT INTO `tbl_district` VALUES ('569', 'Cam Ranh', 'Thị Xã', '56');
INSERT INTO `tbl_district` VALUES ('570', 'Cam Lâm', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('571', 'Vạn Ninh', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('572', 'Ninh Hòa', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('573', 'Khánh Vĩnh', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('574', 'Diên Khánh', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('575', 'Khánh Sơn', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('576', 'Trường Sa', 'Huyện', '56');
INSERT INTO `tbl_district` VALUES ('582', 'Phan Rang-Tháp Chàm', 'Thành Phố', '58');
INSERT INTO `tbl_district` VALUES ('584', 'Bác Ái', 'Huyện', '58');
INSERT INTO `tbl_district` VALUES ('585', 'Ninh Sơn', 'Huyện', '58');
INSERT INTO `tbl_district` VALUES ('586', 'Ninh Hải', 'Huyện', '58');
INSERT INTO `tbl_district` VALUES ('587', 'Ninh Phước', 'Huyện', '58');
INSERT INTO `tbl_district` VALUES ('588', 'Thuận Bắc', 'Huyện', '58');
INSERT INTO `tbl_district` VALUES ('589', 'Thuận Nam', 'Huyện', '58');
INSERT INTO `tbl_district` VALUES ('593', 'Phan Thiết', 'Thành Phố', '60');
INSERT INTO `tbl_district` VALUES ('594', 'La Gi', 'Thị Xã', '60');
INSERT INTO `tbl_district` VALUES ('595', 'Tuy Phong', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('596', 'Bắc Bình', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('597', 'Hàm Thuận Bắc', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('598', 'Hàm Thuận Nam', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('599', 'Tánh Linh', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('600', 'Đức Linh', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('601', 'Hàm Tân', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('602', 'Phú Quí', 'Huyện', '60');
INSERT INTO `tbl_district` VALUES ('608', 'Kon Tum', 'Thành Phố', '62');
INSERT INTO `tbl_district` VALUES ('610', 'Đắk Glei', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('611', 'Ngọc Hồi', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('612', 'Đắk Tô', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('613', 'Kon Plông', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('614', 'Kon Rẫy', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('615', 'Đắk Hà', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('616', 'Sa Thầy', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('617', 'Tu Mơ Rông', 'Huyện', '62');
INSERT INTO `tbl_district` VALUES ('622', 'Pleiku', 'Thành Phố', '64');
INSERT INTO `tbl_district` VALUES ('623', 'An Khê', 'Thị Xã', '64');
INSERT INTO `tbl_district` VALUES ('624', 'Ayun Pa', 'Thị Xã', '64');
INSERT INTO `tbl_district` VALUES ('625', 'Kbang', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('626', 'Đăk Đoa', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('627', 'Chư Păh', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('628', 'Ia Grai', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('629', 'Mang Yang', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('630', 'Kông Chro', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('631', 'Đức Cơ', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('632', 'Chư Prông', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('633', 'Chư Sê', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('634', 'Đăk Pơ', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('635', 'Ia Pa', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('637', 'Krông Pa', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('638', 'Phú Thiện', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('639', 'Chư Pưh', 'Huyện', '64');
INSERT INTO `tbl_district` VALUES ('643', 'Buôn Ma Thuột', 'Thành Phố', '66');
INSERT INTO `tbl_district` VALUES ('644', 'Buôn Hồ', 'Thị Xã', '66');
INSERT INTO `tbl_district` VALUES ('645', 'Ea H\'leo', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('646', 'Ea Súp', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('647', 'Buôn Đôn', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('648', 'Cư M\'gar', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('649', 'Krông Búk', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('650', 'Krông Năng', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('651', 'Ea Kar', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('652', 'M\'đrắk', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('653', 'Krông Bông', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('654', 'Krông Pắc', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('655', 'Krông A Na', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('656', 'Lắk', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('657', 'Cư Kuin', 'Huyện', '66');
INSERT INTO `tbl_district` VALUES ('660', 'Gia Nghĩa', 'Thị Xã', '67');
INSERT INTO `tbl_district` VALUES ('661', 'Đắk Glong', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('662', 'Cư Jút', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('663', 'Đắk Mil', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('664', 'Krông Nô', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('665', 'Đắk Song', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('666', 'Đắk R\'lấp', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('667', 'Tuy Đức', 'Huyện', '67');
INSERT INTO `tbl_district` VALUES ('672', 'Đà Lạt', 'Thành Phố', '68');
INSERT INTO `tbl_district` VALUES ('673', 'Bảo Lộc', 'Thị Xã', '68');
INSERT INTO `tbl_district` VALUES ('674', 'Đam Rông', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('675', 'Lạc Dương', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('676', 'Lâm Hà', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('677', 'Đơn Dương', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('678', 'Đức Trọng', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('679', 'Di Linh', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('680', 'Bảo Lâm', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('681', 'Đạ Huoai', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('682', 'Đạ Tẻh', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('683', 'Cát Tiên', 'Huyện', '68');
INSERT INTO `tbl_district` VALUES ('688', 'Phước Long', 'Thị Xã', '70');
INSERT INTO `tbl_district` VALUES ('689', 'Đồng Xoài', 'Thị Xã', '70');
INSERT INTO `tbl_district` VALUES ('690', 'Bình Long', 'Thị Xã', '70');
INSERT INTO `tbl_district` VALUES ('691', 'Bù Gia Mập', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('692', 'Lộc Ninh', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('693', 'Bù Đốp', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('694', 'Hớn Quản', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('695', 'Đồng Phù', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('696', 'Bù Đăng', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('697', 'Chơn Thành', 'Huyện', '70');
INSERT INTO `tbl_district` VALUES ('703', 'Tây Ninh', 'Thị Xã', '72');
INSERT INTO `tbl_district` VALUES ('705', 'Tân Biên', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('706', 'Tân Châu', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('707', 'Dương Minh Châu', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('708', 'Châu Thành', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('709', 'Hòa Thành', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('710', 'Gò Dầu', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('711', 'Bến Cầu', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('712', 'Trảng Bàng', 'Huyện', '72');
INSERT INTO `tbl_district` VALUES ('718', 'Thủ Dầu Một', 'Thị Xã', '74');
INSERT INTO `tbl_district` VALUES ('720', 'Dầu Tiếng', 'Huyện', '74');
INSERT INTO `tbl_district` VALUES ('721', 'Bến Cát', 'Huyện', '74');
INSERT INTO `tbl_district` VALUES ('722', 'Phú Giáo', 'Huyện', '74');
INSERT INTO `tbl_district` VALUES ('723', 'Tân Uyên', 'Huyện', '74');
INSERT INTO `tbl_district` VALUES ('724', 'Dĩ An', 'Huyện', '74');
INSERT INTO `tbl_district` VALUES ('725', 'Thuận An', 'Huyện', '74');
INSERT INTO `tbl_district` VALUES ('731', 'Biên Hòa', 'Thành Phố', '75');
INSERT INTO `tbl_district` VALUES ('732', 'Long Khánh', 'Thị Xã', '75');
INSERT INTO `tbl_district` VALUES ('734', 'Tân Phú', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('735', 'Vĩnh Cửu', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('736', 'Định Quán', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('737', 'Trảng Bom', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('738', 'Thống Nhất', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('739', 'Cẩm Mỹ', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('740', 'Long Thành', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('741', 'Xuân Lộc', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('742', 'Nhơn Trạch', 'Huyện', '75');
INSERT INTO `tbl_district` VALUES ('747', 'Vũng Tầu', 'Thành Phố', '77');
INSERT INTO `tbl_district` VALUES ('748', 'Bà Rịa', 'Thị Xã', '77');
INSERT INTO `tbl_district` VALUES ('750', 'Châu Đức', 'Huyện', '77');
INSERT INTO `tbl_district` VALUES ('751', 'Xuyên Mộc', 'Huyện', '77');
INSERT INTO `tbl_district` VALUES ('752', 'Long Điền', 'Huyện', '77');
INSERT INTO `tbl_district` VALUES ('753', 'Đất Đỏ', 'Huyện', '77');
INSERT INTO `tbl_district` VALUES ('754', 'Tân Thành', 'Huyện', '77');
INSERT INTO `tbl_district` VALUES ('755', 'Côn Đảo', 'Huyện', '77');
INSERT INTO `tbl_district` VALUES ('760', '1', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('761', '12', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('762', 'Thủ Đức', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('763', '9', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('764', 'Gò Vấp', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('765', 'Bình Thạnh', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('766', 'Tân Bình', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('767', 'Tân Phú', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('768', 'Phú Nhuận', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('769', '2', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('770', '3', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('771', '10', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('772', '11', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('773', '4', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('774', '5', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('775', '6', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('776', '8', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('777', 'Bình Tân', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('778', '7', 'Quận', '79');
INSERT INTO `tbl_district` VALUES ('783', 'Củ Chi', 'Huyện', '79');
INSERT INTO `tbl_district` VALUES ('784', 'Hóc Môn', 'Huyện', '79');
INSERT INTO `tbl_district` VALUES ('785', 'Bình Chánh', 'Huyện', '79');
INSERT INTO `tbl_district` VALUES ('786', 'Nhà Bè', 'Huyện', '79');
INSERT INTO `tbl_district` VALUES ('787', 'Cần Giờ', 'Huyện', '79');
INSERT INTO `tbl_district` VALUES ('794', 'Tân An', 'Thành Phố', '80');
INSERT INTO `tbl_district` VALUES ('796', 'Tân Hưng', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('797', 'Vĩnh Hưng', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('798', 'Mộc Hóa', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('799', 'Tân Thạnh', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('800', 'Thạnh Hóa', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('801', 'Đức Huệ', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('802', 'Đức Hòa', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('803', 'Bến Lức', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('804', 'Thủ Thừa', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('805', 'Tân Trụ', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('806', 'Cần Đước', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('807', 'Cần Giuộc', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('808', 'Châu Thành', 'Huyện', '80');
INSERT INTO `tbl_district` VALUES ('815', 'Mỹ Tho', 'Thành Phố', '82');
INSERT INTO `tbl_district` VALUES ('816', 'Gò Công', 'Thị Xã', '82');
INSERT INTO `tbl_district` VALUES ('818', 'Tân Phước', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('819', 'Cái Bè', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('820', 'Cai Lậy', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('821', 'Châu Thành', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('822', 'Chợ Gạo', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('823', 'Gò Công Tây', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('824', 'Gò Công Đông', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('825', 'Tân Phú Đông', 'Huyện', '82');
INSERT INTO `tbl_district` VALUES ('829', 'Bến Tre', 'Thành Phố', '83');
INSERT INTO `tbl_district` VALUES ('831', 'Châu Thành', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('832', 'Chợ Lách', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('833', 'Mỏ Cày Nam', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('834', 'Giồng Trôm', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('835', 'Bình Đại', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('836', 'Ba Tri', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('837', 'Thạnh Phú', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('838', 'Mỏ Cày Bắc', 'Huyện', '83');
INSERT INTO `tbl_district` VALUES ('842', 'Trà Vinh', 'Thị Xã', '84');
INSERT INTO `tbl_district` VALUES ('844', 'Càng Long', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('845', 'Cầu Kè', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('846', 'Tiểu Cần', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('847', 'Châu Thành', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('848', 'Cầu Ngang', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('849', 'Trà Cú', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('850', 'Duyên Hải', 'Huyện', '84');
INSERT INTO `tbl_district` VALUES ('855', 'Vĩnh Long', 'Thành Phố', '86');
INSERT INTO `tbl_district` VALUES ('857', 'Long Hồ', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('858', 'Mang Thít', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('859', 'Vũng Liêm', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('860', 'Tam Bình', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('861', 'Bình Minh', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('862', 'Trà Ôn', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('863', 'Bình Tân', 'Huyện', '86');
INSERT INTO `tbl_district` VALUES ('866', 'Cao Lãnh', 'Thành Phố', '87');
INSERT INTO `tbl_district` VALUES ('867', 'Sa Đéc', 'Thị Xã', '87');
INSERT INTO `tbl_district` VALUES ('868', 'Hồng Ngự', 'Thị Xã', '87');
INSERT INTO `tbl_district` VALUES ('869', 'Tân Hồng', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('870', 'Hồng Ngự', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('871', 'Tam Nông', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('872', 'Tháp Mười', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('873', 'Cao Lãnh', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('874', 'Thanh Bình', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('875', 'Lấp Vò', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('876', 'Lai Vung', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('877', 'Châu Thành', 'Huyện', '87');
INSERT INTO `tbl_district` VALUES ('883', 'Long Xuyên', 'Thành Phố', '89');
INSERT INTO `tbl_district` VALUES ('884', 'Châu Đốc', 'Thị Xã', '89');
INSERT INTO `tbl_district` VALUES ('886', 'An Phú', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('887', 'Tân Châu', 'Thị Xã', '89');
INSERT INTO `tbl_district` VALUES ('888', 'Phú Tân', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('889', 'Châu Phú', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('890', 'Tịnh Biên', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('891', 'Tri Tôn', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('892', 'Châu Thành', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('893', 'Chợ Mới', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('894', 'Thoại Sơn', 'Huyện', '89');
INSERT INTO `tbl_district` VALUES ('899', 'Rạch Giá', 'Thành Phố', '91');
INSERT INTO `tbl_district` VALUES ('900', 'Hà Tiên', 'Thị Xã', '91');
INSERT INTO `tbl_district` VALUES ('902', 'Kiên Lương', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('903', 'Hòn Đất', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('904', 'Tân Hiệp', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('905', 'Châu Thành', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('906', 'Giồng Giềng', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('907', 'Gò Quao', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('908', 'An Biên', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('909', 'An Minh', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('910', 'Vĩnh Thuận', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('911', 'Phú Quốc', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('912', 'Kiên Hải', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('913', 'U Minh Thượng', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('914', 'Giang Thành', 'Huyện', '91');
INSERT INTO `tbl_district` VALUES ('916', 'Ninh Kiều', 'Quận', '92');
INSERT INTO `tbl_district` VALUES ('917', 'Ô Môn', 'Quận', '92');
INSERT INTO `tbl_district` VALUES ('918', 'Bình Thuỷ', 'Quận', '92');
INSERT INTO `tbl_district` VALUES ('919', 'Cái Răng', 'Quận', '92');
INSERT INTO `tbl_district` VALUES ('923', 'Thốt Nốt', 'Quận', '92');
INSERT INTO `tbl_district` VALUES ('924', 'Vĩnh Thạnh', 'Huyện', '92');
INSERT INTO `tbl_district` VALUES ('925', 'Cờ Đỏ', 'Huyện', '92');
INSERT INTO `tbl_district` VALUES ('926', 'Phong Điền', 'Huyện', '92');
INSERT INTO `tbl_district` VALUES ('927', 'Thới Lai', 'Huyện', '92');
INSERT INTO `tbl_district` VALUES ('930', 'Vị Thanh', 'Thị Xã', '93');
INSERT INTO `tbl_district` VALUES ('931', 'Ngã Bảy', 'Thị Xã', '93');
INSERT INTO `tbl_district` VALUES ('932', 'Châu Thành A', 'Huyện', '93');
INSERT INTO `tbl_district` VALUES ('933', 'Châu Thành', 'Huyện', '93');
INSERT INTO `tbl_district` VALUES ('934', 'Phụng Hiệp', 'Huyện', '93');
INSERT INTO `tbl_district` VALUES ('935', 'Vị Thuỷ', 'Huyện', '93');
INSERT INTO `tbl_district` VALUES ('936', 'Long Mỹ', 'Huyện', '93');
INSERT INTO `tbl_district` VALUES ('941', 'Sóc Trăng', 'Thành Phố', '94');
INSERT INTO `tbl_district` VALUES ('942', 'Châu Thành', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('943', 'Kế Sách', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('944', 'Mỹ Tú', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('945', 'Cù Lao Dung', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('946', 'Long Phú', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('947', 'Mỹ Xuyên', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('948', 'Ngã Năm', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('949', 'Thạnh Trị', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('950', 'Vĩnh Châu', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('951', 'Trần Đề', 'Huyện', '94');
INSERT INTO `tbl_district` VALUES ('954', 'Bạc Liêu', 'Thị Xã', '95');
INSERT INTO `tbl_district` VALUES ('956', 'Hồng Dân', 'Huyện', '95');
INSERT INTO `tbl_district` VALUES ('957', 'Phước Long', 'Huyện', '95');
INSERT INTO `tbl_district` VALUES ('958', 'Vĩnh Lợi', 'Huyện', '95');
INSERT INTO `tbl_district` VALUES ('959', 'Giá Rai', 'Huyện', '95');
INSERT INTO `tbl_district` VALUES ('960', 'Đông Hải', 'Huyện', '95');
INSERT INTO `tbl_district` VALUES ('961', 'Hoà Bình', 'Huyện', '95');
INSERT INTO `tbl_district` VALUES ('964', 'Cà Mau', 'Thành Phố', '96');
INSERT INTO `tbl_district` VALUES ('966', 'U Minh', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('967', 'Thới Bình', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('968', 'Trần Văn Thời', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('969', 'Cái Nước', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('970', 'Đầm Dơi', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('971', 'Năm Căn', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('972', 'Phú Tân', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('973', 'Ngọc Hiển', 'Huyện', '96');
INSERT INTO `tbl_district` VALUES ('974', 'Tây Hồ', 'Quận', '1');
INSERT INTO `tbl_district` VALUES ('975', 'một', 'Type1', '79');
